# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20171122_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.IntegerField(default=1),
        ),
    ]
