# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_question_type_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.BooleanField(),
        ),
    ]
