# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20171122_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type_question',
        ),
        migrations.AddField(
            model_name='question',
            name='job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='nationalite',
            field=models.BooleanField(default=False),
        ),
    ]
