# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_auto_20171122_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='job',
        ),
        migrations.RemoveField(
            model_name='question',
            name='nationalite',
        ),
        migrations.AddField(
            model_name='question',
            name='option',
            field=models.BooleanField(choices=[(True, 'job'), (False, 'nationality')], default=False),
        ),
    ]
